version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/client"
    schedule:
      interval: "daily"
    reviewers:
      - "lhjt"
  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "daily"
    reviewers:
      - "lhjt"
  - package-ecosystem: "cargo"
    directory: "/vl-client"
    schedule:
      interval: "daily"
    reviewers:
      - "lhjt"
