[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
tokio-tungstenite = "0.16.1"
tonic = "0.6.2"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[build-dependencies]
tonic-build = "0.6.2"
