name: CI

on: [push, pull_request]

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    strategy:
      matrix:
        package: [runner, client, server]
        rust: [nightly]
    name: Clippy (${{ matrix.package }})
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --bin ${{ matrix.package }} -- -D warnings
